src/bench.rs
src/bytestr.rs
src/encoder.rs
src/lib.rs
src/reader.rs
src/writer.rs

Fixes `deriving` being renamed to `derive`, and partial fix for
associated types (still need to wait for certain traits to implement
associated types).

Update to latest Rust.

---

src/bytestr.rs
src/lib.rs
src/reader.rs

[This](https://travis-ci.org/BurntSushi/rust-csv/builds/49010538) build failed since there were some changed in the nightly rust builds.  
`FullRange -> RangeFull` (produced an error)
`Show -> Debug` (produced a warning)

FullRange was renamed to RangeFull

---

examples/rational_numbers.rs
src/decoder.rs
src/writer.rs

`FromStr::from_str` now returns `Result` not `Option`.
I'm not sure if we want to do something useful with the error wrapped in `Err`. I currently ignore it.

Make decoder work with newest nightly build.

---

README.md

Solved this error:
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Parse(LocatableError { record: 5, field: 1, err: UnequalLengths { expected: 3, got: 1 } })', ../src/libcore/result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Process didn't exit successfully: `target/debug/stridist` (exit code: 101)
```

make the last example run

---

Cargo.toml
src/lib.rs
src/writer.rs

Extending a Vec using `extend_from_slice` is much faster than extending from an iterator. This reduces the time needed for quoting a string by 40-65% (40% on 50-char strings, 65% on 1000-char strings) if the char contains no escape characters. Also, I think it looks nicer 😃

Use `extend_from_slice` instead of iterator `extend`

---

README.md

Otherwise it will hit `break;` on the first occurrence of `EndOfRecord`, which will always result with a max count of 1.

Don't break on EndOfRecord

---

csv-core/src/reader.rs

This fixes a small grammatical mistake and adds a missing doc comment to `csv-core`.

Small documentation improvements

---

benches/bench.rs
csv-core/src/lib.rs
csv-core/src/reader.rs
csv-core/src/writer.rs
src/deserializer.rs
src/error.rs
src/lib.rs
src/reader.rs
src/serializer.rs
src/string_record.rs
src/writer.rs

It turns out that I hadn't put a lot of work (read: none) into optimizing the CSV writers, and there was a lot left on the table. This PR, among other things, optimizes both the csv-core and csv writers. It also introduces a new public method, `Writer::write_byte_record`, which takes a `&ByteRecord` directly instead of a generic iterator. When given a byte record, it is possible to perform a faster write.
"among other things" are:
* The `QuoteStyle` and `Terminator` types are no longer re-exported through `csv` from `csv-core`, which would make `csv-core` a public dependency on `csv`. Instead, we just re-define the types. We also make exhaustive case analysis impossible on these types so that we may add variants later.
* The `Error` type was changed from a public enum to a struct whose …

optimizations for CSV writing

---

csv-core/src/reader.rs

I was reading your code to see how the DFA transformation worked. The pair of booleans returned from transition_nfa seemed like a "smell," so I changed it to an enum. Tests pass and benchmark results are unchanged (this initialization code isn't the hot-path).
Change transition_nfa to return an NfaInputAction enum instead of a pair of booleans. Only 3 of the 4 possibilities were allowed, enforced by documentation and an assert. Now perhaps slightly clearer what each state transition is doing.

Eliminate "illegal for this to emit an output byte without consuming the input byte" possibility by using an enum

---

src/serializer.rs
src/writer.rs

This PR implements the serialization part of #93. It ended up being more lines changed than I hoped, but a large portion of the changes are new tests and updated documentation. This PR should preserve exsting behavior in the public API, with the exception that some types that used to give an error when called with `serialize` now work.
As part of this PR, I spit off the header serialization functionality into a separate `SeHeader` type. Although this added quite a few lines of code, it made the implementation conceptually simpler. If you'd prefer, I can recombine `SeRecord` and `SeHeader`.
Please let me know if I should make any changes.

Implement serialize for collections of structs

---

src/lib.rs
src/reader.rs
src/writer.rs

I came across this issue when updating the docs for `Writer::serialize` in #94, but I just noticed that it appears elsewhere too. This PR is necessary for the Markdown headings to render correctly, e.g. the `Example` heading for [`csv::invalid_option`](https://docs.rs/csv/1.0.0-beta.5/csv/fn.invalid_option.html).
Edit: Without this PR, there's also an extra space before all of the other lines in the code examples.

Fix alignment of examples in docstrings

---

src/tutorial.rs

Dead link for uspop-null.csv.  Updated with correct link.

Updated link for uspop-null.csv

---

.travis.yml
benches/bench.rs
src/byte_record.rs
src/lib.rs
src/reader.rs
src/string_record.rs

This commit adds support for trimming CSV records. There are two levels
of support:
1. Both `ByteRecord` and `StringRecord` have grown `trim` methods. A
`ByteRecord` trims ASCII whitespace while a `StringRecord` trims
Unicode whitespace.
2. The CSV reader can now be configured to automatically trim all
records that it reads. This is useful when using Serde to match
header names with spaces (for example) to struct member names.
Fixes #78 
---
This PR is based on work by @medwards in #97.

reading: provide trim functionality

---

benches/bench.rs
src/serializer.rs
src/writer.rs

This struct is an implementation detail that allows for progressive
writing of a field into a writer's internal buffer, which means it can
be used as a fmt::Write-r (i.e. with write!), and thus avoid more
temporary allocations with integers and arbitrary user structures (if
they serialize themselves through `Serializer::collect_seq`).
This improves the benchmarks:
name                              before.txt ns/iter     after.txt ns/iter      diff ns/iter   diff %  speedup
count_game_serialize_owned_bytes  14,281,542 (154 MB/s)  13,410,592 (164 MB/s)      -870,950   -6.10%   x 1.06
count_game_serialize_owned_str    14,325,692 (153 MB/s)  13,572,390 (162 MB/s)      -753,302   -5.26%   x 1.06
count_mbta_serialize_owned_bytes  3,238,056 (192 MB/s)   2,645,566 (235 MB/s)       -592,490 …

add SingleFieldWriter for progressive (== faster) serialization

---

src/lib.rs

The link to `Error` is broken.

Fix link to Error struct

---

src/writer.rs

Only flush underlying writer on explicit flush call, not full buffer

---

README.md

By default, code blocks are considered as rust one by rustdoc. To prevent this, you can use whatever strings you want, so I guess "text" is fine. ;)

Fix code block display

---

src/deserializer.rs
tests/tests.rs

Was looking for unsafe code to eliminate and deprecated warnings to resolve. So far I've only done the latter. Please reconsider how you use unsafe code. Yes, this appears safe.. but it'd be nicer if it were simply safe.
Fortunately for me, this is only a transitive dependency via `[dev-dependencies.criterion]` and does not involve user controlled data.
Additionally, as I use a custom `RUST_TARGET_PATH`, I caught the directory traversal hack you're using and replaced it with `env!("CARGO_MANIFEST_DIR")`.

Remove deprecated std::error::Error::description and use CARGO_MANIFEST_DIR to find the examples/data/ for test cases

---

ci/script.sh
csv-core/Cargo.toml

And also, don't run tests in CI on our MSRV since arrayvec has a higher
MSRV.
Closes #182

deps: bump arrayvec to 0.5

---

csv-core/src/writer.rs

I have a debug assertion about the output of `delimiter` being always 1, and I was surprised when this wasn't the case. After looking at the code, it seems that the documentation itself was wrong; it uses one byte to end the quotation and another byte to insert the delimiter, so the maximum output length is not 1, but 2.
Of course, it would be even better if there were a test case to catch this. I happened to catch this with the following CSV:
```
id,name,date,birthday
4,taro,0000/02/13,2020/02/13
5,hoge,2020/02/13,2020/02/13
9999,taro,2020/02/13,2020/02/13
3,taro,2020/bb/13,2020/02/13
98,piyo,2020/02/13,2020/02/13
-1,taro,2020/02/13,2020/02/13
9999,taro,2020/02/13,2020/02/13
5555555555555555555555555555554567898765435678ghdxk jepyfghbx kjeupyf
ghmb jidhm
a,taro,2020/02/13,2020/02/13 …
```

Fix documentation of Writer::delimiter

---

src/byte_record.rs
src/string_record.rs

@BurntSushi what do you think about this? I figured since the diff was so small it'd be easier to discuss over a PR than an issue.
Cloneable iterators are useful when writing code that is generic over
iterators that needs to be able to iterate twice.

Implement Clone for ByteRecordIter and StringRecordIter

---

src/reader.rs
tests/tests.rs

Resolves #207
When reading and parsing a record fails, it's correct behavior in most cases to keep on trying to read and parse the next record.
However when the Error is caused by failing to read from the underlying `impl Read`, the next read would almost always fail with the exact same error.
In that scenario, reading from the underlying `impl Read` should not be attempted when trying to extract the next record, as this may lead to infinite loops.
Instead, the `Reader` will behave in the same way as if an end-of-file had been reached.

Avoid running into infinite loops when recovering from Reader errors

---

src/deserializer.rs

Hi. This is reopening of #198, but with just one of the two commits. Turns out that this is still needed for the suggested solution to work.
If some fields are not required by serde, the `ByteRecord::deserialize` will attempt to skip them by calling `next_field`, which will fail if the skipped field is not valid utf-8. So instead lets skip unused fields using `next_field_bytes`. This affects also `StringRecord::deserialize`, but getting byte slice from string should have no cost. I didn't see any changes in the included benchmarks.

Do not convert to string when skipping unused fields.

---

src/writer.rs

As I was browsing the (great by the way!) documentation for `Writer::serialize`, I noticed a typo... then the second one decided me to do a PR to fix them :wink:

core/doc: fix a few typos in Writer::serialize

---

src/error.rs

Currently, for code that doesn't attempt to recover from errors but just reports the error to the caller, it's forced to return the entire `IntoInnerError`, which is very big compared to `io::Error` which is where the actual error is.
This commit adds `IntoInnerError::into_error()` method that consumes `IntoInnerError` and returns contained `io::Error`. This mirrors the API of [`std::io::IntoInnerError`](https://doc.rust-lang.org/stable/std/io/struct.IntoInnerError.html#method.into_error) in Rust stdlib, which provides such method.

Add IntoInnerError::into_error()

---

src/writer.rs

It's useful to be able to access the underlying writer without dropping `Writer`, for example, checking the position of an `std::io::Cursor`.

Add `Writer::get_ref`

---

.github/workflows/ci.yml
Cargo.toml
README.md
csv-core/src/writer.rs
src/writer.rs

rollup writer comment support, some CI fixes and bump MSRV to Rust 1.61

---

csv-core/src/lib.rs
csv-core/src/reader.rs
csv-core/src/writer.rs
src/error.rs
src/lib.rs

This was introduced in Rust 1.40, which is below the MSRV of 1.73.
It technically breaks any programs which use the undocumented `__Nonexhaustive` variants.
Fixes https://github.com/BurntSushi/rust-csv/issues/325

api: Use `#[non_exhaustive]` instead of `#[doc(hidden)]` variant

---

csv-core/src/lib.rs
csv-core/src/reader.rs
csv-core/src/writer.rs
src/byte_record.rs
src/debug.rs
src/deserializer.rs
src/error.rs
src/lib.rs
src/reader.rs
src/serializer.rs
src/string_record.rs

Address several small Clippy suggestions.

Address Clippy lints

---

tests/tests.rs

https://github.com/rust-lang/rust/pull/115746 made the thread id get printed in panic messages, making the `tutorial_error_01_errored` test fail because it matched on the old panic message format.

test: fix broken test after rust-lang/rust#115746
